# Generated by Django 4.1.7 on 2023-03-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_pin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
