# Generated by Django 4.1.7 on 2023-03-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_pin_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pin_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
